general:
  total_steps: 50
  # total_steps: 200_000
  image_size: [256,512]
  models:
    unet:
      dim: 64
      dim_mults: [1, 2, 4, 8]
      channels: 1

    diffusion:
      timesteps: 1000



data:
  validation_split: 0.1 / 0.9
  csv_file_path: data/datasets/ophthal_anonym/dataset-splitted.csv
  split_seed: 43

training:
  train_loop:
    - name: foo
      foo: foo
    - name: foo
      foo: foo

    - name: train_generator
      diagnosis: reference
      # start_from_checkpoint: 'base_reference_eye_generator'
      lr: 1e-4
      num_steps: 10
      batch_size: 32
      save_and_sample_every: 2000

    - name: foo
      foo: foo

    - name: generate_samples
      repeat: false
      model_path: "123"
      samples_dir: "samples"

output:
  results_dir : .results1111/dupa.111
  # copy_results_to: '~OneDrive/.......'
