general:
  image_size: [256,512]
  models:
    classifier:
      architecture: resnet34
      pretrained: False
      
data:
  validation_split: 0.1 / 0.9
  csv_file_path: data/datasets/ophthal_anonym/dataset-splitted.csv
  split_seed: 42

experiment:
  loop:
######4###### non-str-no-str-tested-non-str
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: synthetic
        train_dataset_dir: data/datasets/synthetic/0001-real-dist
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: non-str-no-str-tested-non-str-synthetic
        logger_group: non-str-no-str-tested-non-str
        logger_tags:
          - synthetic
          - resnet34
          - center-crop
          - average-macro
          - trained-on-non-straified
          - tested-on-non-straified
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: real
        train_dataset_dir: data/datasets/ophthal_anonym_classed/train
        val_dataset_dir: data/datasets/ophthal_anonym_classed/val
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: non-str-no-str-tested-non-str-real
        logger_group: non-str-no-str-tested-non-str
        logger_tags:
          - real
          - resnet34
          - center-crop
          - average-macro
          - trained-on-non-straified
          - tested-on-non-straified
######1###### str-str-tested-str
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: real
        train_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/train
        val_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/val
        test_dataset_dir : data/datasets/ophthal_anonym_classed-stratified/test
        logger_experiment_name: str-str-tested-str-real
        logger_group: str-str-tested-str
        logger_tags:
          - real
          - resnet34
          - center-crop
          - average-macro
          - trained-on-straified
          - tested-on-straified
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: synthetic
        train_dataset_dir: data/datasets/synthetic/0001
        test_dataset_dir : data/datasets/ophthal_anonym_classed-stratified/test
        logger_experment_name: str-str-tested-str-synthetic
        logger_group: str-str-tested-str
        logger_tags:
          - synthetic
          - resnet34
          - center-crop
          - average-macro
          - trained-on-straified
          - tested-on-straified
######2###### non-str-str-tested-non-str
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: real
        train_dataset_dir: data/datasets/ophthal_anonym_classed/train
        val_dataset_dir: data/datasets/ophthal_anonym_classed/val
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: non-str-str-tested-non-str-real
        logger_group: non-str-str-tested-non-str
        logger_tags:
          - real
          - resnet34
          - center-crop
          - average-macro
          - trained-on-non-straified
          - tested-on-non-straified
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: synthetic
        train_dataset_dir: data/datasets/synthetic/0001
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: non-str-str-tested-non-str-synthetic
        logger_group: non-str-str-tested-non-str
        logger_tags:
          - synthetic
          - resnet34
          - center-crop
          - average-macro
          - trained-on-straified
          - tested-on-non-straified
######3###### str-str-tested-non-str
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: real 
        train_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/train
        val_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/val
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: str-str-tested-non-str-real
        logger_group: str-str-tested-non-str
        logger_tags:
          - real
          - resnet34
          - center-crop
          - average-macro
          - trained-on-non-straified
          - tested-on-non-straified
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: synthetic
        train_dataset_dir: data/datasets/synthetic/0001
        test_dataset_dir : data/datasets/ophthal_anonym_classed/test
        logger_experiment_name: str-str-tested-non-str-synthetic
        logger_group: str-str-tested-non-str
        logger_tags:
          - synthetic
          - resnet34
          - center-crop
          - average-macro
          - trained-on-straified
          - tested-on-non-straified
  
output:
  results_dir : .results

