name: medicraft
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - ca-certificates
  - openssl
  - black
  - flake8
  - certifi
  - ipykernel
  - pip
  - pip:
    - denoising_diffusion_pytorch 
    - wandb