general:
  total_steps: 50
  # total_steps: 200_000
  image_size: [256,512]
  models:
    unet:
      dim: 64
      dim_mults: [1, 2, 4, 8]
      channels: 1

    diffusion:
      timesteps: 1000



data:
  val_size: 0.1 / 0.9
  csv_file_path: data/train.csv
  split_seed: 43

training:
  train_loop:
    - name: train_generator
      # output_checkpoint_name: 'base_reference_eye_generator'
      lr: 1e-4
      # move_results_to: '~OneDrive/.......'
    - name: foo
      foo: foo
    - name: generate_samples
      repeat: false
      model_path: "123"
      samples_dir: "samples"

output:
  results_dir : .results
  # move_results_to: '~OneDrive/.......'
