general:
  total_steps: 200_000


data:
  val_size: 0.1 / 0.9
  csv_file_path: data/train.csv
  split_seed: 43

training:
  train_loop:
    - name: train_generator
      output_checkpoint_name: 'base_reference_eye_generator'
      # move_results_to: '~OneDrive/.......'
    - name: foo
      foo: foo

output:
  results_dir : .results
