general:
  image_size: [256,512]
  models:
    classifier:
      architecture: resnet34
      pretrained: False
      
data:
  validation_split: 0.1 / 0.9
  csv_file_path: <dataset-csv-file-path>
  split_seed: 42

#for validation dataloader,dataset should be splitted into train,validation and test dirs containing directories for each class separately
experiment:
  loop:
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: real
        train_dataset_dir: <train-dataset-directory>
        val_dataset_dir: <validation-dataset-directory>
        test_dataset_dir : <test-dataset-directory>
        logger_experiment_name: <experiment-name>
        logger_tags:
          - real
          - resnet34
          
    - name: validate
      classification:
        loss_fn: cross_entropy
        epochs: 15
        lr: 1e-4
        batch_size: 32
        train_data_type: synthetic
        train_dataset_dir: <synthetic dataset path>
        test_dataset_dir : <test-dataset-directory>
        logger_experiment_name: <experiment-name>
        logger_tags:
          - synthetic
          - resnet34
output:
  results_dir : .results
