general:
  image_size: [256,512]
  models:
    unet:
      dim: 64
      dim_mults: [1, 2, 4, 8]
      channels: 1

    diffusion:
      timesteps: 1000
      

data:
  validation_split: 0.1 / 0.9
  csv_file_path: <dataset-csv-file-path>
  split_seed: 42


experiment:
  loop:
    - name: generate_samples
      repeat: false
      relative_dataset_results_dir: <relative-dataset-results-directory>
      num_samples: 1000
      batch_size: 8
      base_on: reference
      model_version: latest
      wandb: false
      


output:
  results_dir : .results
  copy_results_to: <path-to-external-storage>
