general:
  total_steps: 20
  # total_steps: 200_000
  # image_size: [256,512]
  spot_checkpointing: True

  image_size: [128,256]
  models:
    unet:
      dim: 64
      dim_mults: [1, 2, 4, 8]
      channels: 1

    diffusion:
      # timesteps: 1000
      timesteps: 10
    classifier:
      architecture: resnet34
      pretrained: False
      



data:
  validation_split: 0.1 / 0.9
  csv_file_path: data/datasets/ophthal_anonym/dataset-splitted.csv
  split_seed: 43

experiment:
  loop:
    - name: train_generator
      repeat: false
      diagnosis: reference
      # start_from_checkpoint: 'base_reference_eye_generator'
      lr: 1e-4
      num_steps: 20
      batch_size: 2
      num_workers: 8
      gradient_accumulate_every: 8
      save_and_sample_every: 10
      spot_save_every: 5
      start_from_checkpoint: .spot_checkpoint/reference/checkpoint.pt
      wandb_mode: disabled
      # wandb_mode: offline


    - name: foo
      foo: foo
    # - name: generate_samples
    #   repeat: false
    #   relative_dataset_results_dir: datasets/0002
    #   num_samples: 1023
    #   batch_size: 102345
    #   checkpoint: model.pt
    #   base_on: reference
    #   model_version: latest
      

    # - name: validate
    #   classification:
    #     loss_fn: cross_entropy
    #     epochs: 15
    #     lr: 1e-4
    #     batch_size: 32
    #     train_data_type: real
      
    #     train_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/train
    #     val_dataset_dir: data/datasets/ophthal_anonym_classed-stratified/val
    #     test_dataset_dir : data/datasets/ophthal_anonym_classed-stratified/test
  

output:
  results_dir : .results
  # copy_results_to: '~OneDrive/.......'
